### ISSUE TITLE
Erstes Minipiel

### ISSUE THREAD

**Issue by mario-nowak** [serious-games-project-lab-2022/unity-project#3]
- [ ] Add additional shapes (prefab variants of MinigameShapeBase)
- [ ] Generation of valid solution to the game
- [ ] Add button that checks if solution is fulfilled
- [ ] Integration of minigame into pilot scene

The solution to the minigame should be a list of pairwise relative positions between all shapes.

**Comment by mario-nowak** [comment]
This is a test comment! @fredelberger

**Comment by RamzesKh** [comment]
Hello @RhettDuan @fredelberger , ich arbeite aktuell an der Bewegung der Objekten innerhalb eines Gitters ; ) Ich gehe davon aus, dass am Freitag die Implementation fertig wird!

**Comment by mario-nowak** [comment]
Wird erst mal archiviert, weil wir detailliere Issues anlegen.
