### ISSUE TITLE
Place goal in the overworld of the pilot and transition to end scene when reached

### ISSUE THREAD

**Issue by mario-nowak** [serious-games-project-lab-2022/unity-project#34]
After #27, we need to place the `OverworldGoal` prefab in the overworld and transition to an end scene if is reached.
The `GameManager` added in for #31 should listen to the `OverworldGoal`s event and transition the scene accordingly.

**Comment by RamzesKh** [comment]
Hello @RhettDuan , the transition is almost Done!

**Comment by RhettDuan** [comment]
> Hello @RhettDuan , the transition is almost Done!
Now we have to do is just place the overworldgoal whereever we want in the pilot terrain. But only after your pull request with #36 Transition

**Comment by RamzesKh** [comment]
Correct! You could plase the overworldgoal and after merging  with #36 the whole task should be accomplished : )
