### ISSUE TITLE
Add minigame checkpoint prefab

### ISSUE THREAD

**Issue by mario-nowak** [serious-games-project-lab-2022/unity-project#55]
Tasks

- [x] create a `MinigoalCheckpoint` prefab with similar functionality to the current `OverworldGoal`
- [x] It should register, when the spaceship collides with it and emit a static signal
- [x] It should disappear after a collision with the spaceship
- [ ] The `PilotManager` should spawn the minigame after a collision with the spaceship

**Comment by RhettDuan** [comment]
@mario-nowak should we let **Minigamehandler** do the task to spawn the minigame as you said in discord "MinigameHandler: Kümmert sich um das Instanziieren und entfernen der Minispiele"?
